# Generated by Django 2.1.1 on 2018-09-04 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20180903_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='uniqueId',
            new_name='unique_id',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='erp.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='erp.Genre'),
        ),
    ]
