# Generated by Django 2.1.1 on 2018-09-11 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0004_auto_20180904_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBSCRIBER', 'Subscriber'), ('LIBRARIAN', 'Librarian'), ('DIRECTOR', 'Director')], max_length=10)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('BOOK_BOOKS', 'Can book books'), ('CHANGE_BOOKS_STATUS', 'Can change the status of books'), ('CREATE_SUBSCRIBER_ACCOUNTS', 'Can create subscriber accounts'), ('CREATE_LIBRARIAN_ACCOUNTS', 'Can create librarian accounts')),
            },
        ),
    ]
