# Generated by Django 2.1.1 on 2018-09-17 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0009_auto_20180916_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_number_and_street',
            field=models.CharField(default='default address', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address_zipcode',
            field=models.CharField(default=75001, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('BOOKED', 'Booked'), ('MAINTENANCE', 'Maintenance')], default='MAINTENANCE', max_length=20),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
