# Generated by Django 2.1.1 on 2018-09-18 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_auto_20180917_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarian',
            old_name='book_issue',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='book_issue',
            new_name='issue',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='registration_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
