# Generated by Django 2.1.1 on 2018-09-18 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_auto_20180918_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarian',
            old_name='issue',
            new_name='has_rent_issue',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='is_banned',
            new_name='has_rent_issue',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='registration_date',
            new_name='subscription_date',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='issue',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rented_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
