# Generated by Django 2.1.1 on 2018-10-01 11:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_auto_20180925_1639'),
    ]

    operations = [
        # Rename the model `Book` in `GenericBook`
        # and a FK in `BookInstance` pointing to it (from `book` to `generic_book`)
        migrations.AlterField(
            model_name='BookInstance',
            name='book',
            field=models.IntegerField(),
        ),
        migrations.RenameModel('Book', 'GenericBook'),
        migrations.AlterField(
            model_name='BookInstance',
            name='book',
            field=models.ForeignKey(to='erp.GenericBook', related_name='books', on_delete=models.PROTECT),
        ),
        migrations.RenameField('BookInstance', 'book', 'generic_book'),

        # Rename the model `BookInstance` in `Book`
        migrations.RenameModel('BookInstance', 'Book'),

        # Useful reference to rename models with relation on them:
        # https://stackoverflow.com/questions/25091130/django-migration-strategy-for-renaming-a-model-and-relationship-fields/26241640?noredirect=1#comment86571893_26241640
        # take-aways: be incremental and think from the DB viewpoint
    ]


# As a reference here are the generated SQL instructions
# `python manage.py sqlmigrate erp 0016` give a preview of them
#
# BEGIN;
# --
# -- Alter field book on BookInstance
# --
# SET CONSTRAINTS "erp_bookinstance_book_id_f2394b3b_fk_erp_book_id" IMMEDIATE; ALTER TABLE "erp_bookinstance" DROP CONSTRAINT "erp_bookinstance_book_id_f2394b3b_fk_erp_book_id";
# DROP INDEX IF EXISTS "erp_bookinstance_book_id_f2394b3b";
# ALTER TABLE "erp_bookinstance" RENAME COLUMN "book_id" TO "book";
# --
# -- Rename model Book to GenericBook
# --
# ALTER TABLE "erp_book" RENAME TO "erp_genericbook";
# --
# -- Alter field book on BookInstance
# --
# ALTER TABLE "erp_bookinstance" RENAME COLUMN "book" TO "book_id";
# CREATE INDEX "erp_bookinstance_book_id_f2394b3b" ON "erp_bookinstance" ("book_id");
# ALTER TABLE "erp_bookinstance" ADD CONSTRAINT "erp_bookinstance_book_id_f2394b3b_fk_erp_genericbook_id" FOREIGN KEY ("book_id") REFERENCES "erp_genericbook" ("id") DEFERRABLE INITIALLY DEFERRED;
# --
# -- Rename field book on BookInstance to generic_book
# --
# SET CONSTRAINTS "erp_bookinstance_book_id_f2394b3b_fk_erp_book_id" IMMEDIATE; ALTER TABLE "erp_bookinstance" DROP CONSTRAINT "erp_bookinstance_book_id_f2394b3b_fk_erp_book_id";
# ALTER TABLE "erp_bookinstance" RENAME COLUMN "book_id" TO "generic_book_id";
# ALTER TABLE "erp_bookinstance" ADD CONSTRAINT "erp_bookinstance_generic_book_id_90832343_fk_erp_genericbook_id" FOREIGN KEY ("generic_book_id") REFERENCES "erp_genericbook" ("id") DEFERRABLE INITIALLY DEFERRED;
# --
# -- Rename model BookInstance to Book
# --
# ALTER TABLE "erp_bookinstance" RENAME TO "erp_book";
# COMMIT;
