# Generated by Django 2.1.1 on 2018-10-08 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_subscriber_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RENT', 'Rent'), ('BOOKED', 'Booked'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired')], default='MAINTENANCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='due_for',
            field=models.DateField(default=datetime.date(2018, 10, 22)),
        ),
    ]
