# Generated by Django 2.1.2 on 2018-10-28 10:31

from django.db import migrations, models
import erp.models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_auto_20181014_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='has_rent_issue',
            new_name='has_issue',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='received_warning',
            new_name='has_received_warning',
        ),
        migrations.AlterField(
            model_name='rental',
            name='due_for',
            field=models.DateField(default=erp.models.set_due_for),
        ),
    ]
