# Generated by Django 2.1.2 on 2018-10-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_auto_20181028_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='book_withdrawn_during_booking_period',
            new_name='was_cancelled',
        ),
        migrations.AlterField(
            model_name='booking',
            name='was_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
